package dani.java.examenm06uf4.model;
// Generated May 10, 2015 1:47:47 PM by Hibernate Tools 4.3.1



/**
 * Director generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private String cifEmpresa;
     private Empresa empresa;
     private String dni;
     private String nom;
     private String cognoms;
     private String telefon;
     private String email;
     private Double salari;

    public Director() {
    }

	
    public Director(Empresa empresa) {
        this.empresa = empresa;
    }
    public Director(Empresa empresa, String dni, String nom, String cognoms, String telefon, String email, Double salari) {
       this.empresa = empresa;
       this.dni = dni;
       this.nom = nom;
       this.cognoms = cognoms;
       this.telefon = telefon;
       this.email = email;
       this.salari = salari;
    }
   
    public String getCifEmpresa() {
        return this.cifEmpresa;
    }
    
    public void setCifEmpresa(String cifEmpresa) {
        this.cifEmpresa = cifEmpresa;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCognoms() {
        return this.cognoms;
    }
    
    public void setCognoms(String cognoms) {
        this.cognoms = cognoms;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Double getSalari() {
        return this.salari;
    }
    
    public void setSalari(Double salari) {
        this.salari = salari;
    }
    
}


