package dani.java.examenm06uf4.model;
// Generated May 10, 2015 1:47:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleat generated by hbm2java
 */
public class Empleat  implements java.io.Serializable {


     private String dni;
     private String nom;
     private String cognoms;
     private String telefon;
     private String email;
     private Set<Empresa> empresas = new HashSet<>(0);
     private Set<Oficina> oficinas = new HashSet<>(0);

    public Empleat() {
    }

	
    public Empleat(String dni) {
        this.dni = dni;
    }
    public Empleat(String dni, String nom, String cognoms, String telefon, String email, Set<Empresa> empresas, Set<Oficina> oficinas) {
       this.dni = dni;
       this.nom = nom;
       this.cognoms = cognoms;
       this.telefon = telefon;
       this.email = email;
       this.empresas = empresas;
       this.oficinas = oficinas;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCognoms() {
        return this.cognoms;
    }
    
    public void setCognoms(String cognoms) {
        this.cognoms = cognoms;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Oficina> getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Set<Oficina> oficinas) {
        this.oficinas = oficinas;
    }




}


