package dani.java.examenm06uf4.model;
// Generated May 10, 2015 1:47:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String cif;
     private String nom;
     private Boolean ong;
     private String telefon;
     private Date establiment;
     private Set<Empleat> empleats = new HashSet<Empleat>(0);
     private Set<Oficina> oficinas = new HashSet<Oficina>(0);
     private Director director;

    public Empresa() {
    }

	
    public Empresa(String cif) {
        this.cif = cif;
    }
    public Empresa(String cif, String nom, Boolean ong, String telefon, Date establiment, Set<Empleat> empleats, Set<Oficina> oficinas, Director director) {
       this.cif = cif;
       this.nom = nom;
       this.ong = ong;
       this.telefon = telefon;
       this.establiment = establiment;
       this.empleats = empleats;
       this.oficinas = oficinas;
       this.director = director;
    }
   
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Boolean getOng() {
        return this.ong;
    }
    
    public void setOng(Boolean ong) {
        this.ong = ong;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public Date getEstabliment() {
        return this.establiment;
    }
    
    public void setEstabliment(Date establiment) {
        this.establiment = establiment;
    }
    public Set<Empleat> getEmpleats() {
        return this.empleats;
    }
    
    public void setEmpleats(Set<Empleat> empleats) {
        this.empleats = empleats;
    }
    public Set<Oficina> getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Set<Oficina> oficinas) {
        this.oficinas = oficinas;
    }
    public Director getDirector() {
        return this.director;
    }
    
    public void setDirector(Director director) {
        this.director = director;
    }




}


